# Supplementary results table

In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [96]:
supp = pd.read_csv('../results/supplementary.csv')
alphas = sorted(supp.alpha.unique())

In [97]:
supp.head()

,Unnamed: 0,ex_no,variant,alpha,scheme,cv_mean,cv_std,lower_q,upper_q,negshare
0,0,1,hard,0.00,LOO,2.966599,1.975641,-0.599208,8.513508,0.0407
1,1,1,hard,0.00,"hv-block (h=3, v=3)",2.614762,1.910336,-0.894098,8.066245,0.0591
2,2,1,hard,0.50,LOO,4.021484,2.377808,-0.315101,10.805248,0.0185
3,3,1,hard,0.50,"hv-block (h=3, v=3)",2.624827,1.923599,-0.922499,8.104686,0.0596
4,4,1,hard,0.75,LOO,3.254179,2.779811,-2.318025,11.045192,0.1007

In [98]:
supp.scheme.unique()

array(['LOO', 'hv-block (h=3, v=3)'], dtype=object)

In [99]:
schemes = ['LOO', 'hv-block (h=3, v=3)']

In [100]:
table = []
for i in range(1, 6+1):
    for s in schemes:
        rec = {
            'experiment': f'Experiment {i}',
            'scheme': s,
        }
        for v in ['easy', 'hard']:
            for a in alphas:
                err = supp[(supp.ex_no == i) & (supp.alpha == a) & (supp.scheme == s) & (supp.variant == v)].negshare
                rec[f'{v} {a:.2f}'] = 100*round(float(err),3) if len(err) else None
        table.append(rec)

tabledf = pd.DataFrame(table)
tabledf

,experiment,scheme,easy 0.00,easy 0.50,easy 0.75,easy 1.00,hard 0.00,hard 0.50,hard 0.75,hard 1.00
0,Experiment 1,LOO,0.0,0.0,0.0,9.1,4.1,1.8,10.1,93.9
1,Experiment 1,"hv-block (h=3, v=3)",0.0,0.0,0.0,0.0,5.9,6.0,7.3,14.8
2,Experiment 2,LOO,0.0,0.0,0.0,1.5,0.0,0.0,0.0,1.0
3,Experiment 2,"hv-block (h=3, v=3)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Experiment 3,LOO,0.0,0.0,0.0,2.5,4.1,1.5,8.7,82.9
5,Experiment 3,"hv-block (h=3, v=3)",0.0,0.0,0.0,0.0,5.9,4.8,4.6,7.8
6,Experiment 4,LOO,0.0,0.0,0.0,85.7,4.5,6.3,28.8,98.5
7,Experiment 4,"hv-block (h=3, v=3)",0.0,0.0,0.0,92.8,5.0,8.6,32.9,98.7
8,Experiment 5,LOO,33.4,0.0,0.0,0.0,10.8,0.3,0.2,0.0
9,Experiment 5,"hv-block (h=3, v=3)",23.5,0.0,0.0,0.0,23.2,0.0,0.0,0.0
10,Experiment 6,LOO,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.1
11,Experiment 6,"hv-block (h=3, v=3)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [101]:
table = []
for i in range(1, 6+1):
    for s in schemes:
        rec = {
            'experiment': f'Experiment {i}',
            'scheme': s,
        }
        for v in ['easy', 'hard']:
            for a in alphas:
                std = supp[(supp.ex_no == i) & (supp.alpha == a) & (supp.scheme == s) & (supp.variant == v)].cv_std
                rec[f'{v} {a:.2f}'] = round(float(std),2) if len(err) else None
        table.append(rec)

tabledf = pd.DataFrame(table)
tabledf

,experiment,scheme,easy 0.00,easy 0.50,easy 0.75,easy 1.00,hard 0.00,hard 0.50,hard 0.75,hard 1.00
0,Experiment 1,LOO,5.35,6.26,8.32,10.59,1.98,2.38,2.78,2.37
1,Experiment 1,"hv-block (h=3, v=3)",5.36,5.37,5.38,4.77,1.91,1.92,1.88,1.54
2,Experiment 2,LOO,6.13,7.68,9.99,11.76,6.11,7.54,9.59,10.46
3,Experiment 2,"hv-block (h=3, v=3)",6.07,6.23,6.33,5.89,6.06,6.19,6.27,5.81
4,Experiment 3,LOO,5.35,6.47,8.74,10.90,1.98,2.50,3.02,2.83
5,Experiment 3,"hv-block (h=3, v=3)",5.36,5.38,5.42,5.02,1.91,1.98,2.00,1.75
6,Experiment 4,LOO,5.33,3.84,2.60,0.41,1.95,1.73,1.21,0.24
7,Experiment 4,"hv-block (h=3, v=3)",5.33,3.90,2.69,0.50,1.96,1.76,1.26,0.29
8,Experiment 5,LOO,0.68,4.81,7.68,8.91,0.24,1.53,2.75,8.94
9,Experiment 5,"hv-block (h=3, v=3)",0.85,5.43,7.40,10.86,0.84,4.78,8.01,15.20
10,Experiment 6,LOO,7.04,7.86,9.60,11.23,6.27,7.32,8.72,6.60
11,Experiment 6,"hv-block (h=3, v=3)",7.04,6.97,6.87,6.12,6.19,6.16,6.05,5.24